sudo: required
services:
    - docker
    
before_install:
    - docker build -t wizard1988/docker-react -f Dockerfile.dev .
    
script:
    - docker run -e CI=true wizard1988/docker-react npm run test