sudo: required
services:
    - docker
    
before_install:
    - docker build -t wizard1988/docker-react -f Dockerfile.dev .
    
script:
    - docker run -e CI=true wizard1988/docker-react npm run test
    
deploy:
    provider: elasticbeanstalk
    region: "ap-south-1"
    app: "docker-react"
    env: "DockerReact-env"
    bucket_name: "elasticbeanstalk-ap-south-1-009372046761"
    bucket_path: "docker-react"
    on:
        branch: master
    acces_key_id: $AWS_ACCESS_KEY
    secret_access_key:
        secure: "$AWS_SECRET_KEY"
